CREATE DATABASE DEVWEBCAMP;
USE DEVWEBCAMP;

CREATE TABLE USERS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	lastname VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
	confirmed TINYINT DEFAULT 0,
    admin TINYINT DEFAULT 0,
	token VARCHAR(15) DEFAULT NULL
); 

CREATE TABLE SPEAKERS ( 
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    lastname VARCHAR(40) NOT NULL,
    city VARCHAR(20) NOT NULL,
    country VARCHAR(20) NOT NULL,
    image VARCHAR(32) DEFAULT NULL,
    tags VARCHAR(120) DEFAULT NULL,
    networks TEXT DEFAULT NULL
);